version: '3.9'

services:
  api:
    build: api
    ports:
      - "172.16.0.1:6598:8000"
    env_file:
      - api/.env
    external_links:
      - db-pg:db-pg
    volumes:
      - './api/:/api'
    restart: always




  bot:
    build: bot
    external_links:
      - db-pg:db-pg
    env_file:
      - bot/.env
    environment:
      DEBUG: 'true'
    restart: always
    volumes:
      - './bot/:/bot'

  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - bot/.env
    ports:
      - "5432:5432"
    container_name: db-pg


volumes:
  postgres_data:
  api:
  bot: